# Generated by Django 5.1.7 on 2025-03-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_type',
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterModelTable(
            name='vote',
            table='votes',
        ),
    ]
